#!/usr/bin/env bash
#
# Render the hrafnagud Secret from the deploy env file and print the path of
# the rendered file on stdout. The caller applies it and deletes it.
#
#   f=$(deploy/k8s/render-secret.sh) && kubectl apply -f "$f"; rm -f "$f"
#
# There is no secret.yaml in the repository, and no template with
# placeholders either — the manifest is generated here so the keys have
# exactly one definition. Values are base64-encoded into `data:` rather than
# written as `stringData:` text, because a password containing a quote, a
# backslash or a leading `*` would otherwise produce either broken YAML or,
# worse, silently different content.
#
# GitOps setups (sealed-secrets, SOPS, External Secrets) should create a
# Secret named `hrafnagud-secrets` in the target namespace with the same
# three keys instead of using this script; the Deployment only references
# the name.

set -euo pipefail

# shellcheck source=../lib/common.sh
. "$(cd "$(dirname "${BASH_SOURCE[0]}")/../lib" && pwd)/common.sh"

load_deploy_env

require_var HRAFNAGUD_MONGO_URI

b64() { printf '%s' "${1:-}" | base64 | tr -d '\n'; }

out="$(mktemp -t hrafnagud-secret.XXXXXX)"
chmod 600 "${out}"

cat > "${out}" <<EOF
# Generated by deploy/k8s/render-secret.sh — do not commit.
apiVersion: v1
kind: Secret
metadata:
  name: hrafnagud-secrets
  namespace: ${K8S_NAMESPACE}
  labels:
    app: hrafnagud
type: Opaque
data:
  # Values are quoted so that an unset one renders as "" rather than as a
  # YAML null, which is not a valid base64 payload.
  #
  # Full connection string including credentials, e.g.
  # mongodb://user:pass@host:27017/hrafnagud?authSource=admin
  HRAFNAGUD_MONGO_URI: "$(b64 "${HRAFNAGUD_MONGO_URI}")"
  # Bearer token for the operator API at /api/v1/**, and therefore for the
  # console. Empty means no check at all — and this API deletes as well as
  # reads, so in a cluster it should never be empty.
  HRAFNAGUD_API_TOKEN: "$(b64 "${HRAFNAGUD_API_TOKEN:-}")"
  # Ursa event token for the brain-side translation kit. Empty is fine; the
  # translation subsystem is inert unless VANCE_BRAIN_URL is set too.
  VANCE_TRANSLATE_TOKEN: "$(b64 "${VANCE_TRANSLATE_TOKEN:-}")"
  # Google AI key for the other translation path — the model called directly
  # instead of through a brain. Empty means that provider is not wired; with
  # both wired, HRAFNAGUD_TRANSLATION_PROVIDER in the ConfigMap decides.
  GEMINI_API_KEY: "$(b64 "${GEMINI_API_KEY:-}")"
  # Bearer key guarding the Centauri feed endpoint. Empty means no check at
  # all — acceptable only behind a proxy that authenticates for it.
  HRAFNAGUD_CENTAURI_API_KEY: "$(b64 "${HRAFNAGUD_CENTAURI_API_KEY:-}")"
  # The same, for the search endpoint. A separate key on purpose: the two
  # surfaces are enabled separately, and a leak should cost one of them.
  HRAFNAGUD_ZARNIWOOP_API_KEY: "$(b64 "${HRAFNAGUD_ZARNIWOOP_API_KEY:-}")"
EOF

echo "${out}"
