package de.mhus.hrafnagud.munin.content;

import de.mhus.hrafnagud.munin.util.TextCleaner;
import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jspecify.annotations.Nullable;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.json.JsonMapper;

/**
 * Reads {@code schema.org} article metadata out of a page's JSON-LD blocks.
 *
 * <p>This is the first rung of the extraction ladder, and it is qualitatively
 * different from the rungs below it: the heuristics guess at what the markup
 * means, whereas this asks the publisher and gets an answer. Nearly every
 * news site emits it, because Google News requires it — so the coverage is
 * far better than the effort suggests.
 *
 * <p>The parsing is defensive throughout. Real-world JSON-LD is generated by
 * templates and is malformed often enough that a strict reader would lose a
 * large share of it: {@code @type} is a string or an array, {@code image} is
 * a string or an object or an array of either, {@code author} is an object
 * or a list, and the whole document may be wrapped in an {@code @graph}. A
 * block that cannot be parsed is skipped rather than failing the page —
 * there is always the DOM to fall back on.
 */
@Slf4j
public final class JsonLdReader {

    /**
     * {@code @type} values treated as an article. Publishers use several
     * interchangeably, and a site that labels its reports
     * {@code ReportageNewsArticle} is not less of a news site for it.
     */
    private static final Set<String> ARTICLE_TYPES = Set.of(
            "newsarticle", "article", "reportagenewsarticle", "backgroundnewsarticle",
            "opinionnewsarticle", "analysisnewsarticle", "reviewnewsarticle",
            "blogposting", "liveblogposting", "socialmediaposting", "report");

    /** Bounds the walk of a deeply nested or hostile document. */
    private static final int MAX_DEPTH = 6;

    private static final ObjectMapper MAPPER = JsonMapper.builder().build();

    private JsonLdReader() {
    }

    /**
     * Returns the first article-typed JSON-LD object in the document, or
     * {@link JsonLdArticle#absent()} when there is none.
     */
    public static JsonLdArticle read(Document document) {
        for (Element script : document.select("script[type=application/ld+json]")) {
            JsonNode root = parse(script.data());
            if (root == null) {
                continue;
            }
            JsonNode article = findArticle(root, 0);
            if (article != null) {
                return toArticle(article);
            }
        }
        return JsonLdArticle.absent();
    }

    private static @Nullable JsonNode parse(String raw) {
        String json = StringUtils.trimToEmpty(raw);
        if (json.isEmpty()) {
            return null;
        }
        try {
            return MAPPER.readTree(json);
        } catch (RuntimeException e) {
            // Jackson 3 throws unchecked. Malformed JSON-LD is common enough
            // that this is a routine outcome, not an error worth a warning.
            log.trace("JsonLdReader: unparseable block: {}", e.toString());
            return null;
        }
    }

    /**
     * Depth-first search for an article-typed object, descending through
     * arrays and {@code @graph} wrappers.
     */
    private static @Nullable JsonNode findArticle(JsonNode node, int depth) {
        if (depth > MAX_DEPTH) {
            return null;
        }
        if (node.isArray()) {
            for (JsonNode child : node) {
                JsonNode found = findArticle(child, depth + 1);
                if (found != null) {
                    return found;
                }
            }
            return null;
        }
        if (!node.isObject()) {
            return null;
        }
        if (isArticleType(node.get("@type"))) {
            return node;
        }
        JsonNode graph = node.get("@graph");
        return graph == null ? null : findArticle(graph, depth + 1);
    }

    private static boolean isArticleType(@Nullable JsonNode type) {
        if (type == null) {
            return false;
        }
        if (type.isArray()) {
            for (JsonNode entry : type) {
                if (isArticleType(entry)) {
                    return true;
                }
            }
            return false;
        }
        return ARTICLE_TYPES.contains(
                StringUtils.trimToEmpty(type.stringValue()).toLowerCase(Locale.ROOT));
    }

    private static JsonLdArticle toArticle(JsonNode node) {
        JsonLdArticle.JsonLdArticleBuilder builder = JsonLdArticle.builder().present(true);

        builder.headline(clean(text(node, "headline")));
        builder.description(clean(text(node, "description")));
        builder.language(StringUtils.trimToNull(text(node, "inLanguage")));
        builder.author(clean(nameOf(node.get("author"))));
        builder.datePublished(instant(text(node, "datePublished")));

        // articleBody arrives with real newlines; those are the paragraph
        // structure and must survive the whitespace normalisation that the
        // other fields get.
        String body = text(node, "articleBody");
        builder.articleBody(StringUtils.isBlank(body) ? null : normalizeBody(body));

        collectImages(node.get("image")).forEach(builder::image);
        collectStrings(node.get("articleSection")).forEach(builder::section);

        return builder.build();
    }

    /**
     * {@code image} is a URL, an {@code ImageObject}, or an array of either —
     * all three occur in the wild, sometimes on the same site.
     */
    private static List<String> collectImages(@Nullable JsonNode node) {
        List<String> urls = new ArrayList<>();
        if (node == null) {
            return urls;
        }
        if (node.isArray()) {
            for (JsonNode entry : node) {
                urls.addAll(collectImages(entry));
            }
            return urls;
        }
        if (node.isObject()) {
            String url = text(node, "url");
            if (StringUtils.isNotBlank(url)) {
                urls.add(url.trim());
            }
            return urls;
        }
        String value = StringUtils.trimToEmpty(node.stringValue());
        if (!value.isEmpty()) {
            urls.add(value);
        }
        return urls;
    }

    private static List<String> collectStrings(@Nullable JsonNode node) {
        List<String> values = new ArrayList<>();
        if (node == null) {
            return values;
        }
        if (node.isArray()) {
            for (JsonNode entry : node) {
                values.addAll(collectStrings(entry));
            }
            return values;
        }
        String value = clean(node.isObject() ? text(node, "name") : node.stringValue());
        if (StringUtils.isNotBlank(value)) {
            values.add(value);
        }
        return values;
    }

    /** {@code author} is an object, a bare string, or a list of either. */
    private static String nameOf(@Nullable JsonNode node) {
        if (node == null) {
            return "";
        }
        if (node.isArray()) {
            List<String> names = new ArrayList<>();
            for (JsonNode entry : node) {
                String name = nameOf(entry);
                if (StringUtils.isNotBlank(name)) {
                    names.add(name);
                }
            }
            return String.join(", ", names);
        }
        return node.isObject() ? text(node, "name") : StringUtils.trimToEmpty(node.stringValue());
    }

    private static String text(JsonNode node, String field) {
        JsonNode value = node.get(field);
        return value == null || !value.isValueNode() ? "" : value.stringValue();
    }

    /**
     * Parses an ISO-8601 timestamp. Publishers emit offsets, {@code Z}, and
     * occasionally a bare local date-time; only the first two are accepted,
     * because guessing a time zone would put an article in the wrong hour.
     */
    private static @Nullable Instant instant(String value) {
        String trimmed = StringUtils.trimToEmpty(value);
        if (trimmed.isEmpty()) {
            return null;
        }
        try {
            return OffsetDateTime.parse(trimmed).toInstant();
        } catch (DateTimeParseException e) {
            try {
                return Instant.parse(trimmed);
            } catch (DateTimeParseException ignored) {
                log.trace("JsonLdReader: unparseable datePublished '{}'", trimmed);
                return null;
            }
        }
    }

    /** Collapses horizontal whitespace but keeps paragraph breaks. */
    private static String normalizeBody(String body) {
        String unified = body.replace("\r\n", "\n").replace('\r', '\n');
        StringBuilder out = new StringBuilder(unified.length());
        for (String paragraph : unified.split("\n{2,}")) {
            String line = TextCleaner.normalizeWhitespace(paragraph);
            if (line.isEmpty()) {
                continue;
            }
            if (out.length() > 0) {
                out.append("\n\n");
            }
            out.append(line);
        }
        return out.toString();
    }

    private static @Nullable String clean(String value) {
        return StringUtils.trimToNull(TextCleaner.stripHtml(value));
    }
}
