#!/usr/bin/env python3
"""Regenerates the bundled IPTC Media Topics table.

    scripts/generate-mediatopics-tsv.py

Writes src/main/resources/topics/iptc-mediatopics.tsv, fetching the
vocabulary from IPTC unless a local copy is passed as the first argument.

Why this exists at all: the first version of the table was generated by a
throwaway script, and when a bug turned up in the normalisation there was no
way to rebuild it. A bundled resource nobody can regenerate is a resource
nobody can fix.

The normalisation here MUST match CategoryKeys.normalise in Java. The whole
point of the table is that a category string normalised at runtime can be
compared against a label normalised at build time; if the two disagree, the
matcher silently stops resolving things and no test fails.
"""
import json
import re
import sys
import unicodedata
import urllib.request
from pathlib import Path

SOURCE = "https://cv.iptc.org/newscodes/mediatopic/?format=json"
TARGET = (Path(__file__).resolve().parent.parent
          / "src/main/resources/topics/iptc-mediatopics.tsv")

# Mirrors CategoryKeys.normalise: NFKD, combining marks dropped, lowercased,
# anything that is not a letter or digit collapsed to a single space.
#
# Note what it deliberately does NOT do: fold to ASCII. That was the original
# bug — it folded Latin accents correctly and annihilated every other script,
# so the Arabic and Chinese labels (a quarter of the vocabulary) were dropped
# here, and any Cyrillic or Persian category normalised to the empty string at
# runtime and could never be mapped at all.
NON_ALNUM = re.compile(r"[\W_]+", re.UNICODE)


def normalise(raw: str) -> str:
    decomposed = unicodedata.normalize("NFKD", raw.strip())
    stripped = "".join(c for c in decomposed
                       if not unicodedata.category(c).startswith("M"))
    return NON_ALNUM.sub(" ", stripped.lower()).strip()


def labels_of(concept: dict) -> list[str]:
    """Every distinct normalised label of one concept, in a stable order."""
    seen: dict[str, None] = {}
    for field in ("prefLabel", "altLabel"):
        for value in (concept.get(field) or {}).values():
            for label in (value if isinstance(value, list) else [value]):
                key = normalise(label)
                if key:
                    seen[key] = None
    return sorted(seen)


def parent_of(concept: dict, by_uri: dict[str, str]) -> str | None:
    """The parent as a qcode.

    ``broader`` holds URIs, not qcodes, and writing them through unchanged
    produces a table that loads without complaint and has no hierarchy at all:
    1,393 roots, every path one element long, every depth 1. Resolving through
    the scheme's own uri→qcode index rather than string surgery means a changed
    URI form breaks loudly here instead of quietly flattening the tree.
    """
    for broader in concept.get("broader") or []:
        if isinstance(broader, dict):
            reference = broader.get("qcode") or broader.get("uri")
        else:
            reference = broader
        if not reference:
            continue
        if reference in by_uri:
            return by_uri[reference]
        if reference.startswith("medtop:"):
            return reference
        raise SystemExit(f"unresolvable broader reference {reference!r} "
                         f"on {concept['qcode']}")
    return None


def main() -> int:
    if len(sys.argv) > 1:
        data = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
    else:
        print(f"fetching {SOURCE}")
        with urllib.request.urlopen(SOURCE, timeout=120) as response:
            data = json.loads(response.read().decode("utf-8"))

    concepts = data["conceptSet"]
    languages = sorted({lang
                        for c in concepts
                        for field in ("prefLabel", "altLabel")
                        for lang in (c.get(field) or {})})

    by_uri = {c["uri"]: c["qcode"] for c in concepts if c.get("uri")}

    rows = []
    for concept in concepts:
        qcode = concept["qcode"]
        name = (concept.get("prefLabel") or {}).get("en-GB") or qcode
        rows.append((qcode, parent_of(concept, by_uri) or "-",
                     name.replace("\t", " ").strip(), labels_of(concept)))
    rows.sort(key=lambda r: r[0])

    # A vocabulary of 1,393 concepts five levels deep has a handful of roots. If
    # this ever passes with hundreds, the hierarchy has been lost and nothing
    # downstream will say so — paths collapse to one element and every concept
    # starts looking like a top-level term.
    root_count = sum(1 for r in rows if r[1] == "-")
    if root_count > 50:
        raise SystemExit(f"{root_count} concepts have no parent — the broader "
                         f"references did not resolve")

    licence = data.get("licenceLink", "")
    total_labels = sum(len(r[3]) for r in rows)
    roots = sum(1 for r in rows if r[1] == "-")

    with TARGET.open("w", encoding="utf-8") as out:
        out.write(f"""\
# IPTC Media Topics — the vocabulary article categories are normalised against.
#
# Source: IPTC NewsCodes, http://cv.iptc.org/newscodes/mediatopic/
# Licence: CC BY 4.0 ({licence}) — "you can use them for free in any way, but
# we request that you give IPTC credit".
# Modified: projected to id/parent/name plus normalised labels for matching;
# definitions, dates and non-label metadata dropped.
#
# GENERATED by scripts/generate-mediatopics-tsv.py — do not edit by hand. The
# normalisation below must stay identical to CategoryKeys.normalise in Java.
#
# Columns: qcode <TAB> parentQcode <TAB> name(en-GB) <TAB> labels('|'-separated)
# Labels are normalised: NFKD, combining marks dropped, lowercased, non-alphanumeric
# to single spaces. Non-Latin scripts are preserved, NOT folded away.
# Languages: {' '.join(languages)}
""")
        for qcode, parent, name, labels in rows:
            out.write(f"{qcode}\t{parent}\t{name}\t{'|'.join(labels)}\n")

    print(f"{TARGET.relative_to(TARGET.parents[4])}: {len(rows)} concepts, "
          f"{roots} roots, {total_labels} labels, "
          f"{len(languages)} languages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
